/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF, useTexture } from "@react-three/drei";

export function Foundation(props) {
  const { nodes, materials } = useGLTF("/foundation.glb");
  const texture = useTexture("./WoodFlooringAshBrickBondEbonyDark001_flat.jpg");

  //frustum called all

  return (
    <group {...props} dispose={null}>
      <group
        position={[2.49191, 1.51204, -4.38172]}
        scale={[0.56538, 1, 0.56538]}
      >
        <mesh
          frustumCulled={false}
          castShadow
          receiveShadow
          geometry={nodes.Cube041.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_1.geometry}
          material={materials.rims}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_2.geometry}
          material={materials["window-glass"]}
        >
          <meshPhysicalMaterial
            color="white"
            attach="material"
            roughness={0.3}
            opacity={0.5}
            transparent
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_3.geometry}
          material={materials["wall-plugs"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_4.geometry}
          material={materials["tile-bg-kitchen"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041_5.geometry}
          material={materials["wall paint"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.block.geometry}
        material={materials.Material}
        position={[0, 0.0053, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor.geometry}
        position={[-0.0006, 0.01204, -0.00195]}
      >
        <meshStandardMaterial attach="material" roughness={0.8} map={texture} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/foundation.glb");
