/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Furniture(props) {
  const { nodes, materials } = useGLTF("/house-furniture.glb");
  return (
    <group position={[0, 0.01, 0]} {...props} dispose={null}>
      <group position={[-4.12, 0.45, -4.24]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials["tv-metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials["tv-screen"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials["tv-plastic"]}
        />
      </group>
      <group position={[-5.12, 2.23, 1.89]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials["lamp-metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.towel.geometry}
        material={materials["Material.007"]}
        position={[-4.61, 1.3, -0.01]}
        rotation={[0.32, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["washing-rack"].geometry}
        material={nodes["washing-rack"].material}
        position={[-5.8, 1.04, -0.37]}
      />
      <group position={[-4.08, 0.61, -2]} rotation={[Math.PI / 2, 0, -1.62]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={materials["salon-table-metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011_1.geometry}
          material={materials["test-wood"]}
        />
      </group>
      <group position={[-4.12, 0.33, -4.15]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials["test-wood"]}
        />
      </group>
      <group position={[0.27, 0.13, 0.32]} scale={[1, 1, 0.98]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={materials["salon-table-metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026_1.geometry}
          material={materials["test-wood"]}
        />
      </group>
      <group position={[-5.13, 0.26, 1.5]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials["salon-table-metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials["test-wood"]}
        />
      </group>
      <group position={[-6.41, 0.11, -0.57]} rotation={[0, -1.57, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube022_1.geometry}
          material={materials["test-fabric"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rug.geometry}
        material={materials["test-fabric"]}
        position={[-4, 0.01, -1.96]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["pillow-4"].geometry}
        material={materials["test-fabric"]}
        position={[-3.38, 0.91, -1.08]}
        rotation={[-1.16, 0.23, 0.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["pillow-1"].geometry}
        material={materials["test-fabric"]}
        position={[-3.81, 0.91, -1.08]}
        rotation={[-1.16, -0.22, -0.47]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["pillow-2"].geometry}
        material={materials["test-fabric"]}
        position={[-3.63, 0.86, -1.3]}
        rotation={[-0.1, -0.29, -0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["pillow-3"].geometry}
        material={materials["test-fabric"]}
        position={[-5.92, 0.91, -1.13]}
        rotation={[-1.09, -0.84, -0.84]}
      />
      <group position={[-5.78, 0.78, 1.79]} rotation={[0, 1.34, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={materials["salon-table-metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013_1.geometry}
          material={materials["test-fabric"]}
        />
      </group>
      <group position={[-4.54, 0.78, 2.86]} rotation={[0, -1.43, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={materials["salon-table-metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014_1.geometry}
          material={materials["test-fabric"]}
        />
      </group>
      <group
        position={[-5.78, 0.78, 2.94]}
        rotation={[-Math.PI, 1.49, -Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials["salon-table-metal"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials["test-fabric"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/house-furniture.glb");
