/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Kitchen(props) {
  const { nodes, materials } = useGLTF("/kitchen.glb");
  return (
    <group position={[0.13, -3, 0]} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["wall-plug-2001"].geometry}
        material={materials["wall-plugs"]}
        position={[2.41, 1.57, -4.3]}
        rotation={[0, -0.84, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={materials["stove-under"]}
        position={[1.33, 1.34, -4.2]}
        scale={0.22}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials["stove-up"]}
        position={[1.09, 1.13, -4.2]}
        scale={0.04}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={materials["stove-up"]}
        position={[1.06, 1.13, -4.2]}
        scale={0.04}
      />
      <group position={[1.55, 1.15, -4.3]} scale={[0.04, 0.03, 0.04]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials["stove-up"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials["stove-metal"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={materials["stove-up"]}
        position={[1.1, 1.15, -4.23]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={materials["stove-up"]}
        position={[1.52, 1.15, -4.23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={materials.suction}
        position={[1.37, 2.33, -4.34]}
        scale={0.21}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["stove-under"]}
        position={[2.48, 1.37, -2.62]}
        scale={0.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["salon-table-metal"]}
        position={[1.37, 0.96, -3.93]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={materials["salon-table-metal"]}
        position={[1.37, 0.79, -3.93]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials["salon-table-metal"]}
        position={[1.37, 0.96, -3.93]}
        scale={0.4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["salon-table-metal"]}
        position={[1.36, 0.85, -3.92]}
        scale={0.06}
      />
      <group position={[2.31, 0.64, -2.91]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube032_1.geometry}
          material={materials["stove-under"]}
        />
      </group>
      <group position={[1.04, 0.64, -4.21]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube033_1.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.009"]}
        position={[2.38, 2.65, -2.77]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Material.009"]}
        position={[-0.4, 1.46, -4.21]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.003"]}
        position={[1.74, 1.1, -3.48]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials["Material.009"]}
        position={[-0.4, 1.18, -4.24]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Material.009"]}
        position={[-0.4, 0.64, -3.93]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Material.009"]}
        position={[0.47, 0.43, -3.93]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["Material.009"]}
        position={[0.47, 0.75, -3.93]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["Material.009"]}
        position={[0.47, 0.96, -3.93]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["Material.009"]}
        position={[1.37, 0.32, -3.93]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={materials["Material.009"]}
        position={[2.03, 0.65, -3.38]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["Material.009"]}
        position={[2.03, 0.65, -2.57]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={materials["Material.009"]}
        position={[2.03, 0.65, -1.76]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={materials["Material.009"]}
        position={[1.71, 1.23, -3.36]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={materials["Material.009"]}
        position={[1.71, 1.23, -2.55]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials["Material.009"]}
        position={[1.71, 1.23, -1.74]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.handles.geometry}
        material={materials["lamp-metal"]}
        position={[-0.01, 1.18, -3.9]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials["stove-under"]}
        position={[2.27, 1.12, -2.61]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.02}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials["stove-under"]}
        position={[1.74, 1.1, -3.48]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["kitchen-tiles"].geometry}
        material={materials["kitchen-tiles"]}
        position={[-0.74, 1.62, -4.49]}
        rotation={[-Math.PI, -1.57, 0]}
        scale={[1, 0.87, 0.98]}
      />
    </group>
  );
}

useGLTF.preload("/kitchen.glb");
